# Generated by Django 4.0.5 on 2022-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_code', models.IntegerField()),
                ('lang_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'texts',
                'ordering': ['text_code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=2000)),
                ('weight', models.CharField(max_length=250)),
                ('from_location', models.CharField(max_length=2000)),
                ('sender_name', models.CharField(max_length=250)),
                ('sender_phone', models.CharField(max_length=13)),
                ('to_location', models.CharField(max_length=250)),
                ('recipient_name', models.CharField(max_length=250)),
                ('recipient_phone', models.CharField(max_length=13)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('order_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('weight', models.CharField(blank=True, max_length=250, null=True)),
                ('from_location', models.CharField(blank=True, max_length=2000, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=250, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('to_location', models.CharField(blank=True, max_length=250, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('step', models.IntegerField(default=0)),
                ('is_self', models.BooleanField(default=True)),
                ('delete_message', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('data_birthday', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user')),
                ('step', models.IntegerField(default=0)),
                ('del_message', models.IntegerField(blank=True, null=True)),
                ('lang', models.CharField(default='uz', max_length=5)),
                ('address', models.CharField(blank=True, max_length=4096, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'telegram_user',
                'verbose_name_plural': 'telegram_users',
                'ordering': ['id'],
            },
        ),
    ]
