# Generated by Django 4.0.5 on 2022-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_order_comment_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_location',
            field=models.CharField(max_length=2000, verbose_name='Откуда забрать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=2000, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=250, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(max_length=13, verbose_name='Номер получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_name',
            field=models.CharField(max_length=250, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(max_length=13, verbose_name='Номер отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_location',
            field=models.CharField(max_length=250, verbose_name='Куда доставить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(max_length=250, verbose_name='Вес товара'),
        ),
    ]
