# Generated by Django 4.0.5 on 2022-07-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_order_comment_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandText',
            new_name='B2CCommandText',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='B2COrder',
        ),
        migrations.RenameModel(
            old_name='Step',
            new_name='B2CStep',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='B2CUser',
        ),
    ]
