# Generated by Django 4.0.5 on 2022-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_rename_commandtext_b2ccommandtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_price_order', models.CharField(max_length=250, verbose_name='Тип доставки')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('price1', models.IntegerField(blank=True, null=True, verbose_name='Цена (0-3Кг)')),
                ('price2', models.IntegerField(blank=True, null=True, verbose_name='Цена (3-6Кг)')),
                ('price3', models.IntegerField(blank=True, null=True, verbose_name='Цена (6-9Кг)')),
                ('price4', models.IntegerField(blank=True, null=True, verbose_name='Цена (9-12Кг)')),
                ('price5', models.IntegerField(blank=True, null=True, verbose_name='Цена (12-15Кг)')),
                ('price6', models.IntegerField(blank=True, null=True, verbose_name='Цена (12 Кг ->)')),
            ],
            options={
                'verbose_name': 'Б2С Настройки цена',
                'verbose_name_plural': 'Б2С Настройки цены',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='b2corder',
            options={'ordering': ['id'], 'verbose_name': 'Б2С Заказ', 'verbose_name_plural': 'Б2С Заказы'},
        ),
        migrations.AlterModelOptions(
            name='b2cuser',
            options={'ordering': ['id'], 'verbose_name': 'Б2С Пользовател', 'verbose_name_plural': 'Б2С Пользователи'},
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='address',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='data_birthday',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя Пользователя'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='Имя Пользователя'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия Пользователя'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер Пользователя'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ид'),
        ),
        migrations.AlterField(
            model_name='b2cuser',
            name='username',
            field=models.CharField(max_length=250, verbose_name='Телеграм профил'),
        ),
    ]
