# Generated by Django 4.0.5 on 2022-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_b2cprice_alter_b2corder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
