# Generated by Django 4.0.5 on 2022-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_b2corder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cstep',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
