# Generated by Django 4.0.5 on 2022-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_b2cstep_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cstep',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
    ]
