# Generated by Django 4.0.5 on 2022-08-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B2CStaff', '0004_alter_kuryer_balance'),
        ('tgbot', '0010_alter_b2corder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='kuryer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='B2CStaff.kuryer'),
        ),
    ]
