# Generated by Django 4.0.5 on 2022-08-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_b2corder_is_safe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2cprice',
            old_name='percentage',
            new_name='percent',
        ),
    ]
