# Generated by Django 4.0.5 on 2022-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_rename_percentage_b2cprice_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='after_image',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Вторая картинка'),
        ),
        migrations.AddField(
            model_name='b2corder',
            name='before_image',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Первая картинка'),
        ),
    ]
