# Generated by Django 4.0.5 on 2022-08-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0016_b2corder_after_image_b2corder_before_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2corder',
            name='del_message',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
