# Generated by Django 4.0.5 on 2022-08-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0017_b2corder_del_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2ccommandtext',
            options={'ordering': ['text_code'], 'verbose_name': 'Текст команды', 'verbose_name_plural': 'Текст команды'},
        ),
        migrations.AddField(
            model_name='b2corder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='is_safe',
            field=models.BooleanField(default=False, verbose_name='Безопасно'),
        ),
        migrations.AlterField(
            model_name='b2corder',
            name='status',
            field=models.CharField(blank=True, default='Заказ оформлен', max_length=250, null=True, verbose_name='Статус'),
        ),
    ]
