# Generated by Django 4.0.5 on 2022-07-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2CStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuryer',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты'),
        ),
        migrations.AlterField(
            model_name='kuryer',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Баланс'),
        ),
    ]
