# Generated by Django 4.0.5 on 2022-07-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2CStaff', '0002_kuryer_payment_date_alter_kuryer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher_telegram_id', models.BigIntegerField(verbose_name='Диспетчер Telegram ID')),
                ('dispatcher_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя диспетчера')),
            ],
            options={
                'verbose_name': 'Диспетчер',
                'verbose_name_plural': 'Диспетчеры',
            },
        ),
    ]
