# Generated by Django 4.0.5 on 2022-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2CStaff', '0003_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuryer',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс'),
        ),
    ]
