# Generated by Django 4.0.5 on 2022-08-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2CStaff', '0004_alter_kuryer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuryer',
            name='kuryer_b2c',
        ),
        migrations.RemoveField(
            model_name='kuryer',
            name='kuryer_driver',
        ),
        migrations.AddField(
            model_name='kuryer',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
