# Generated by Django 4.0.5 on 2022-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2CStaff', '0005_remove_kuryer_kuryer_b2c_remove_kuryer_kuryer_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuryer',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус'),
        ),
    ]
